//! Renders `tasks/archive/INDEX.md` — the tier-grouped index of archived
//! tasks — from the on-disk archive tree.
//!
//! The whole file is generated content: a full rewrite, no managed block.
//! [`write_archive_index`] is called by `ark archive` after a real (non
//! dry-run) move so the index is always a faithful projection of the tree.

use std::fmt::Write as _;

use crate::{
    commands::agent::state::{TaskToml, Tier},
    error::Result,
    io::{PathExt, write_atomic},
    layout::Layout,
};

/// A single archived task as it appears in the index.
struct Entry {
    /// Tier from the task's `task.toml` — drives which section groups the row.
    tier: Tier,
    /// On-disk tier directory name — used to build the link so it always
    /// points at the directory actually walked, even if it disagrees with
    /// `tier` (a `task.toml`-only or directory-only tier edit).
    tier_dir: String,
    month: String,
    slug: String,
    title: String,
}

/// Tier sections render in this fixed order; empty tiers are omitted.
const TIER_ORDER: [Tier; 4] = [Tier::Deep, Tier::Standard, Tier::Quick, Tier::Research];

/// Writes the rendered index to `tasks/archive/INDEX.md`.
///
/// Renders from the on-disk tree and writes atomically. A no-op-safe full
/// rewrite: the file's entire content is generated, so re-running produces
/// byte-identical output for an unchanged tree.
///
/// # Errors
///
/// Propagates filesystem errors from walking the archive or writing the file.
pub fn write_archive_index(layout: &Layout) -> Result<()> {
    let body = render_archive_index(layout)?;
    // The index lives at the archive root; ensure it exists so the atomic
    // write's sibling temp file has a home even on a fresh tree.
    layout.tasks_archive_dir().ensure_dir()?;
    write_atomic(layout.tasks_archive_index(), body.as_bytes())
}

/// Returns the full Markdown body of the archive index.
///
/// Walks `tasks/archive/<YYYY-MM>/<tier>/<slug>/`, groups entries by tier in
/// [`TIER_ORDER`], and within each tier sorts rows by month then slug. Tiers
/// with no archived tasks are omitted. An empty archive yields the header
/// alone.
///
/// # Errors
///
/// Propagates filesystem errors from reading the archive tree.
pub fn render_archive_index(layout: &Layout) -> Result<String> {
    let entries = collect_entries(layout)?;

    let mut out = String::new();
    out.push_str("# Archived Tasks\n\n");
    out.push_str(
        "Closed tasks, grouped by tier. Layout on disk is `<YYYY-MM>/<tier>/<slug>/`.\nWithin a \
         tier, rows are sorted by month then slug. Regenerated by `ark archive`.\n",
    );

    for tier in TIER_ORDER {
        let mut rows: Vec<&Entry> = entries.iter().filter(|e| e.tier == tier).collect();
        if rows.is_empty() {
            continue;
        }
        rows.sort_by(|a, b| a.month.cmp(&b.month).then_with(|| a.slug.cmp(&b.slug)));

        let _ = write!(out, "\n## {} ({})\n\n", tier.dir_name(), rows.len());
        out.push_str("| Month | Task | Title |\n|-------|------|-------|\n");
        for e in rows {
            // Link uses the walked directory name (`tier_dir`), not `tier`, so
            // it points at the directory that actually exists on disk.
            let _ = writeln!(
                out,
                "| {} | [{}]({}/{}/{}/) | {} |",
                e.month, e.slug, e.month, e.tier_dir, e.slug, e.title,
            );
        }
    }

    Ok(out)
}

/// Walks the archive tree and returns one [`Entry`] per task with a readable
/// `task.toml`. Directories whose `task.toml` is missing or unparseable are
/// skipped silently — the index reports what is present, not what is broken.
fn collect_entries(layout: &Layout) -> Result<Vec<Entry>> {
    let archive_root = layout.tasks_archive_dir();
    if !archive_root.is_dir() {
        return Ok(Vec::new());
    }
    let mut entries = Vec::new();
    for month_entry in archive_root.list_dir()? {
        let month_path = month_entry
            .map_err(|e| crate::error::Error::io(&archive_root, e))?
            .path();
        if !month_path.is_dir() {
            continue;
        }
        let Some(month) = month_path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        for tier_entry in month_path.list_dir()? {
            let tier_path = tier_entry
                .map_err(|e| crate::error::Error::io(&month_path, e))?
                .path();
            if !tier_path.is_dir() {
                continue;
            }
            let Some(tier_dir) = tier_path.file_name().and_then(|n| n.to_str()) else {
                continue;
            };
            for task_entry in tier_path.list_dir()? {
                let task_path = task_entry
                    .map_err(|e| crate::error::Error::io(&tier_path, e))?
                    .path();
                if !task_path.is_dir() {
                    continue;
                }
                let Some(slug) = task_path.file_name().and_then(|n| n.to_str()) else {
                    continue;
                };
                let Ok(toml) = TaskToml::load(&task_path) else {
                    continue;
                };
                entries.push(Entry {
                    tier: toml.tier,
                    tier_dir: tier_dir.to_string(),
                    month: month.to_string(),
                    slug: slug.to_string(),
                    title: toml.title,
                });
            }
        }
    }
    Ok(entries)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Seeds an archived task directory at `<month>/<tier>/<slug>/`.
    fn seed(layout: &Layout, month: &str, tier: Tier, slug: &str, title: &str) {
        let dir = layout
            .tasks_archive_dir()
            .join(month)
            .join(tier.dir_name())
            .join(slug);
        dir.ensure_dir().unwrap();
        dir.join("task.toml")
            .write_bytes(
                format!(
                    "id = \"{slug}\"\ntitle = \"{title}\"\ntier = \"{}\"\nphase = \
                     \"archived\"\ncreated_at = \"2026-05-01T00:00:00Z\"\nupdated_at = \
                     \"2026-05-01T00:00:00Z\"\narchived_at = \"2026-05-01T00:00:00Z\"\n",
                    tier.dir_name(),
                )
                .as_bytes(),
            )
            .unwrap();
    }

    /// Renders a multi-tier tree: sections appear in deep/standard/quick order,
    /// each with its count, rows sorted month-then-slug, empty tiers omitted.
    #[test]
    fn render_archive_index_matches_tree() {
        let tmp = tempfile::tempdir().unwrap();
        let layout = Layout::new(tmp.path());
        seed(&layout, "2026-05", Tier::Quick, "bravo", "b task");
        seed(&layout, "2026-04", Tier::Quick, "alpha", "a task");
        seed(&layout, "2026-05", Tier::Deep, "delta", "d task");

        let body = render_archive_index(&layout).unwrap();

        // Deep section precedes quick; research absent (no entries).
        let deep_at = body.find("## deep (1)").unwrap();
        let quick_at = body.find("## quick (2)").unwrap();
        assert!(deep_at < quick_at, "deep must precede quick:\n{body}");
        assert!(!body.contains("## standard"), "no standard tasks:\n{body}");
        assert!(!body.contains("## research"), "no research tasks:\n{body}");

        // Quick rows sorted month-then-slug: 2026-04/alpha before 2026-05/bravo.
        let alpha_at = body.find("[alpha](2026-04/quick/alpha/)").unwrap();
        let bravo_at = body.find("[bravo](2026-05/quick/bravo/)").unwrap();
        assert!(
            alpha_at < bravo_at,
            "rows must sort month-then-slug:\n{body}"
        );
    }

    /// An empty archive yields the header only — no tier sections, no panic.
    #[test]
    fn render_archive_index_empty_tree_is_header_only() {
        let tmp = tempfile::tempdir().unwrap();
        let layout = Layout::new(tmp.path());
        let body = render_archive_index(&layout).unwrap();
        assert!(body.starts_with("# Archived Tasks"));
        assert!(!body.contains("##"), "no tier sections expected:\n{body}");
    }

    /// Builds the link from the walked directory name, so a row whose
    /// `task.toml` tier disagrees with its on-disk tier directory still links
    /// to the directory that exists.
    #[test]
    fn render_link_uses_walked_dir_not_toml_tier() {
        let tmp = tempfile::tempdir().unwrap();
        let layout = Layout::new(tmp.path());
        // A task.toml claiming `deep` placed in a `quick/` directory on disk.
        let dir = layout
            .tasks_archive_dir()
            .join("2026-05")
            .join("quick")
            .join("mismatch");
        dir.ensure_dir().unwrap();
        // Legacy archived deep task: still carries the retired `iteration` key,
        // which must load as an ignored unknown field.
        dir.join("task.toml")
            .write_bytes(
                b"id = \"mismatch\"\ntitle = \"m\"\ntier = \"deep\"\nphase = \"archived\"\n\
                  iteration = 0\ncreated_at = \"2026-05-01T00:00:00Z\"\nupdated_at = \
                  \"2026-05-01T00:00:00Z\"\narchived_at = \"2026-05-01T00:00:00Z\"\n",
            )
            .unwrap();

        let body = render_archive_index(&layout).unwrap();
        // Grouped under the toml tier (deep), but linked to the real dir (quick).
        assert!(body.contains("## deep (1)"), "{body}");
        assert!(
            body.contains("[mismatch](2026-05/quick/mismatch/)"),
            "link must use the walked dir:\n{body}"
        );
    }

    /// `write_archive_index` is idempotent: a second run over an unchanged tree
    /// produces byte-identical output.
    #[test]
    fn write_archive_index_is_idempotent() {
        let tmp = tempfile::tempdir().unwrap();
        let layout = Layout::new(tmp.path());
        seed(&layout, "2026-05", Tier::Standard, "solo", "s task");

        write_archive_index(&layout).unwrap();
        let first = layout.tasks_archive_index().read_text().unwrap();
        write_archive_index(&layout).unwrap();
        let second = layout.tasks_archive_index().read_text().unwrap();
        assert_eq!(first, second);
    }
}
