name: CI

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-04-11
          components: rustfmt, clippy

      - name: Format
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Test
        run: cargo test --workspace
